version : "3.4"

services:
  api : 
    build : 
      context : .
      target : development,
    environment:
      - MONGO_URI=mongodb://mongodb:27017/user_management
    volumes : 
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports : 
      - 3000:3000
    command : npm run dev

  mongodb-myapp:
      image: mongo
      ports:
        - "27017:27017"